### ISSUE TITLE
Modificar el lenguaje

### ISSUE THREAD

**Issue by PedroRamosRguez** [PedroRamosRguez/100daysofcode#6]
Modificar a ingles la app

**Comment by s-Hale** [comment]
Puedo ayudarte. A ver... el Readme puedo hacer ahora. ¿Quieres que los nombres del funciones y las variables etc en los archivos javascript que sea traducido también?

**Comment by PedroRamosRguez** [comment]
Ohhh muchas gracias je je pero no es necesario.. lo puse porque como es el challenge de #100daysofcode lo puse como un recordatorio. Muchas gracias de todas maneras 😁. El tema del challenge es que es para trabajar solo. Y luego cuando la app ya esté terminada, si la comunidad quiere aportar algo pues bienvenido es ^^.
